In [12]:
import regex as re
import numpy as np
from tqdm.auto import tqdm

In [60]:
with open("lord-of-the-rings-processed.txt", "r") as f:
    text = f.read()
print(f"Total length of the books is {len(text)}")

Total length of the books is 3729707


In [4]:
vocab = {bytes([i]):i for i in range(256)}

In [8]:
vocab[b" "]

32

In [81]:
text[:100]

'The Music of the Ainur There was Eru, the One, who in Arda is called lluvatar; and he made first the'

In [61]:
text[-20:]

"I'm back,' he said. "

In [72]:
text2 = "<|startofchapter|>" + text
text2[:20]

'<|startofchapter|>Th'

# experiment

In [88]:
pattern = r"""'(?i:[sdmt]|ll|ve|re)|[^\r\n\p{L}\p{N}]?+\p{L}+|\p{N}{1,3}| ?[^\s\p{L}\p{N}]++[\r\n]*|\s*[\r\n]|\s+(?!\S)|\s+"""
pattern2 = re.compile(r""" ?<\|[a-z]+\|>|'(?i:[sdmt]|ll|ve|re)|[^\r\n\p{L}\p{N}]?+\p{L}+|\p{N}{1,3}| ?[^\s\p{L}\p{N}]++[\r\n]*|\s*[\r\n]|\s+(?!\S)|\s+""")
compiled_pattern = re.compile(pattern)
compiled_pattern

regex.Regex("'(?i:[sdmt]|ll|ve|re)|[^\\r\\n\\p{L}\\p{N}]?+\\p{L}+|\\p{N}{1,3}| ?[^\\s\\p{L}\\p{N}]++[\\r\\n]*|\\s*[\\r\\n]|\\s+(?!\\S)|\\s+", flags=regex.V0)

In [75]:
re.findall(pattern2,text2[:20])

['<|startofchapter|>', 'Th']

In [4]:
sample = text

In [89]:
text_chunks = re.findall(compiled_pattern,text)
print(len(text_chunks))

826401


In [90]:
text_chunks_new = re.findall(pattern2,text2)
print(len(text_chunks_new))

826402


In [91]:
text_chunks[:20]

['The',
 ' Music',
 ' of',
 ' the',
 ' Ainur',
 ' There',
 ' was',
 ' Eru',
 ',',
 ' the',
 ' One',
 ',',
 ' who',
 ' in',
 ' Arda',
 ' is',
 ' called',
 ' lluvatar',
 ';',
 ' and']

In [92]:
text_chunks_new[:20]

['<|startofchapter|>',
 'The',
 ' Music',
 ' of',
 ' the',
 ' Ainur',
 ' There',
 ' was',
 ' Eru',
 ',',
 ' the',
 ' One',
 ',',
 ' who',
 ' in',
 ' Arda',
 ' is',
 ' called',
 ' lluvatar',
 ';']

In [93]:
difference = list(set(text_chunks_new) - set(text_chunks))
difference

['<|startofchapter|>']

In [46]:
print(text_chunks[:10])

['The', ' Music', ' of', ' the', ' Ainur', ' There', ' was', ' Eru', ',', ' the']


In [57]:
list((text_chunks[0].encode("utf-8")))

[84, 104, 101]

In [58]:
token_chunks = [list(chunk.encode("utf-8")) for chunk in text_chunks]
print(len(token_chunks))

826401


In [19]:
def get_pair_counts(tokens,pairs={}):
    for (c1,c2) in zip(tokens[:-1],tokens[1:]):
        pairs[(c1,c2)] = pairs.get((c1,c2),0) + 1
    return pairs

In [20]:
pair_counts={}
print(len(sample))
pair_counts = get_pair_counts(sample)
sorted_pair_counts = sorted(pair_counts.items(),key=lambda x: x[1], reverse=True)
sorted_pair_counts[:20]

3729707


[(('e', ' '), 122267),
 ((' ', 't'), 107301),
 (('t', 'h'), 97454),
 (('h', 'e'), 95711),
 (('d', ' '), 85094),
 ((' ', 'a'), 74312),
 (('t', ' '), 66737),
 (('s', ' '), 60306),
 (('a', 'n'), 52657),
 (('i', 'n'), 51884),
 (('n', 'd'), 50578),
 ((' ', 's'), 47191),
 ((' ', 'w'), 46516),
 ((' ', 'h'), 46059),
 (('n', ' '), 44394),
 (('e', 'r'), 42105),
 ((',', ' '), 41681),
 (('r', 'e'), 41576),
 ((' ', 'o'), 41228),
 (('r', ' '), 35267)]

In [50]:
pair_counts2 = {}
for chunks in token_chunks:
    pair_counts2 = get_pair_counts(chunks,pairs=pair_counts2)


In [22]:
sorted_pairs_counts2 = sorted(pair_counts2.items(),key=lambda x:x[1], reverse=True)
sorted_pairs_counts2[:20]

[((32, 116), 107301),
 ((116, 104), 97453),
 ((104, 101), 95711),
 ((32, 97), 74312),
 ((97, 110), 52657),
 ((105, 110), 51884),
 ((110, 100), 50578),
 ((32, 115), 47191),
 ((32, 119), 46516),
 ((32, 104), 46059),
 ((101, 114), 42105),
 ((114, 101), 41576),
 ((32, 111), 41228),
 ((111, 117), 31075),
 ((104, 97), 29690),
 ((101, 100), 29597),
 ((32, 105), 29194),
 ((111, 114), 29095),
 ((110, 103), 28596),
 ((32, 98), 27952)]

In [24]:
token_chunks[:10]

[[84, 104, 101],
 [32, 77, 117, 115, 105, 99],
 [32, 111, 102],
 [32, 116, 104, 101],
 [32, 65, 105, 110, 117, 114],
 [32, 84, 104, 101, 114, 101],
 [32, 119, 97, 115],
 [32, 69, 114, 117],
 [44],
 [32, 116, 104, 101]]

In [23]:
len_token_chunks = list(map(len,token_chunks))
len_token_chunks[:10]

[3, 6, 3, 4, 6, 6, 4, 4, 1, 4]

In [29]:
np.mean(len_token_chunks)

4.5151530552358965

In [51]:
top_pair = max(pair_counts2,key=pair_counts2.get)
top_pair

(32, 116)

In [30]:
def merge_top_pair(token_chunk,pair,new_token):
    new_tokens = []
    i = 0
    while i < len(token_chunk):
        if i < len(token_chunk)-1 and (token_chunk[i], token_chunk[i+1]) == pair:
            new_tokens.append(new_token)
            i += 2
        else:
            new_tokens.append(token_chunk[i])
            i += 1
    return new_tokens

In [61]:
token_chunks2 = [merge_top_pair(chunk,top_pair,257) for chunk in token_chunks]

In [33]:
len_token_chunks2 = list(map(len,token_chunks2))
len_token_chunks2[:10]

[3, 6, 3, 3, 6, 6, 4, 4, 1, 3]

In [53]:
np.mean(len_token_chunks2)

4.385311731229754

In [54]:
token_chunks[:10]

[array([ 84, 104, 101]),
 array([ 32,  77, 117, 115, 105,  99]),
 array([ 32, 111, 102]),
 array([ 32, 116, 104, 101]),
 array([ 32,  65, 105, 110, 117, 114]),
 array([ 32,  84, 104, 101, 114, 101]),
 array([ 32, 119,  97, 115]),
 array([ 32,  69, 114, 117]),
 array([44]),
 array([ 32, 116, 104, 101])]

In [62]:
token_chunks2[:10]

[[84, 104, 101],
 [32, 77, 117, 115, 105, 99],
 [32, 111, 102],
 [257, 104, 101],
 [32, 65, 105, 110, 117, 114],
 [32, 84, 104, 101, 114, 101],
 [32, 119, 97, 115],
 [32, 69, 114, 117],
 [44],
 [257, 104, 101]]

In [63]:
len(token_chunks2)

826401

In [67]:
with open("test.npy","wb") as f:
    np.save(f,len(token_chunks2))
    for chunk in token_chunks2:
        np.save(f,chunk)

In [73]:
with open("test.npy","rb") as f:
    token_chunks3 = []
    token_length = np.load(f)
    for _ in range(token_length.item()):
        token_chunks3.append(np.load(f))

In [74]:
token_chunks3

[array([ 84, 104, 101]),
 array([ 32,  77, 117, 115, 105,  99]),
 array([ 32, 111, 102]),
 array([257, 104, 101]),
 array([ 32,  65, 105, 110, 117, 114]),
 array([ 32,  84, 104, 101, 114, 101]),
 array([ 32, 119,  97, 115]),
 array([ 32,  69, 114, 117]),
 array([44]),
 array([257, 104, 101]),
 array([ 32,  79, 110, 101]),
 array([44]),
 array([ 32, 119, 104, 111]),
 array([ 32, 105, 110]),
 array([ 32,  65, 114, 100,  97]),
 array([ 32, 105, 115]),
 array([ 32,  99,  97, 108, 108, 101, 100]),
 array([ 32, 108, 108, 117, 118,  97, 116,  97, 114]),
 array([59]),
 array([ 32,  97, 110, 100]),
 array([ 32, 104, 101]),
 array([ 32, 109,  97, 100, 101]),
 array([ 32, 102, 105, 114, 115, 116]),
 array([257, 104, 101]),
 array([ 32,  65, 105, 110, 117, 114]),
 array([44]),
 array([257, 104, 101]),
 array([ 32,  72, 111, 108, 121]),
 array([ 32,  79, 110, 101, 115]),
 array([44]),
 array([257, 104,  97, 116]),
 array([ 32, 119, 101, 114, 101]),
 array([257, 104, 101]),
 array([ 32, 111, 102, 10

In [75]:
pair_counts3 = {}
for chunks in token_chunks3:
    pair_counts3 = get_pair_counts(chunks,pairs=pair_counts3)
top_pair = max(pair_counts3,key=pair_counts3.get)
top_pair

(104, 101)

In [76]:
token_chunks4 = [merge_top_pair(chunk,top_pair,258) for chunk in token_chunks3]

In [77]:
len(token_chunks4)

826401

In [78]:
len_token_chunks4 = list(map(len,token_chunks4))
len_token_chunks4[:10]

[2, 6, 3, 2, 6, 5, 4, 4, 1, 2]

In [79]:
np.mean(len_token_chunks4)

4.269495075635194

In [173]:
len(token_chunks2)

826401

In [153]:
token_chunks2[:20]

[[84, 104, 101],
 [32, 77, 117, 115, 105, 99],
 [32, 111, 102],
 [257, 104, 101],
 [32, 65, 105, 110, 117, 114],
 [32, 84, 104, 101, 114, 101],
 [32, 119, 97, 115],
 [32, 69, 114, 117],
 [44],
 [257, 104, 101],
 [32, 79, 110, 101],
 [44],
 [32, 119, 104, 111],
 [32, 105, 110],
 [32, 65, 114, 100, 97],
 [32, 105, 115],
 [32, 99, 97, 108, 108, 101, 100],
 [32, 108, 108, 117, 118, 97, 116, 97, 114],
 [59],
 [32, 97, 110, 100]]

In [154]:
token_chunks2[-20:]

[[32, 104, 105, 115],
 [32, 108, 97, 112],
 [46],
 [32, 72, 101],
 [32, 100, 114, 101, 119],
 [32, 97],
 [32, 100, 101, 101, 112],
 [32, 98, 114, 101, 97, 116, 104],
 [46],
 [32, 39],
 [87, 101, 108, 108],
 [44],
 [32, 73],
 [39, 109],
 [32, 98, 97, 99, 107],
 [44, 39],
 [32, 104, 101],
 [32, 115, 97, 105, 100],
 [46],
 [32]]

In [157]:
token_chunks_str = str(token_chunks2)
token_chunks_str2 = token_chunks_str[1:-2]
token_chunks_str2 = token_chunks_str2.replace("[","")

In [158]:
print(token_chunks_str2[:100])
print(token_chunks_str2[-100:])

84, 104, 101], 32, 77, 117, 115, 105, 99], 32, 111, 102], 257, 104, 101], 32, 65, 105, 110, 117, 114
4], 32, 73], 39, 109], 32, 98, 97, 99, 107], 44, 39], 32, 104, 101], 32, 115, 97, 105, 100], 46], 32


In [159]:


token_chunks_str2 = token_chunks_str2.replace("]," ,"\n")
token_chunks_str2 = token_chunks_str2.replace(",","")
print(token_chunks_str2[:100])
print("-------------------------------------------------")
print(token_chunks_str2[-100:])

84 104 101
 32 77 117 115 105 99
 32 111 102
 257 104 101
 32 65 105 110 117 114
 32 84 104 101 114 
-------------------------------------------------
39
 87 101 108 108
 44
 32 73
 39 109
 32 98 97 99 107
 44 39
 32 104 101
 32 115 97 105 100
 46
 32


In [163]:
with open("test.txt","w") as f:
    f.write(token_chunks_str2)

In [164]:
with open("test.txt","r") as f:
    chunks = f.read()


In [165]:
chunks[-100:]

'39\n 87 101 108 108\n 44\n 32 73\n 39 109\n 32 98 97 99 107\n 44 39\n 32 104 101\n 32 115 97 105 100\n 46\n 32'

In [166]:
def recover_chunks(text):
    token_chunks = [[int(num) for num in block.strip().split(" ")] for block in text.split("\n")]
    return token_chunks

In [167]:
chunks_recovered = recover_chunks(chunks)

In [168]:
chunks_recovered[:20]

[[84, 104, 101],
 [32, 77, 117, 115, 105, 99],
 [32, 111, 102],
 [257, 104, 101],
 [32, 65, 105, 110, 117, 114],
 [32, 84, 104, 101, 114, 101],
 [32, 119, 97, 115],
 [32, 69, 114, 117],
 [44],
 [257, 104, 101],
 [32, 79, 110, 101],
 [44],
 [32, 119, 104, 111],
 [32, 105, 110],
 [32, 65, 114, 100, 97],
 [32, 105, 115],
 [32, 99, 97, 108, 108, 101, 100],
 [32, 108, 108, 117, 118, 97, 116, 97, 114],
 [59],
 [32, 97, 110, 100]]

In [172]:
chunks_recovered == token_chunks2

True

True